/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kazurayam.vba.parsing;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
